import fs from 'fs-extra';
import path from 'path';
import type { Label } from '../types.js';

const OUTPUT_DIR = './taggr';

/**
 * Convert kebab-case to camelCase
 */
function toCamelCase(str: string): string {
  return str.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
}

/**
 * Generate labels.json content
 */
function generateLabelsJson(labels: Label[]): string {
  const labelsObj: Record<string, string> = {};
  for (const label of labels) {
    const key = toCamelCase(label.name);
    labelsObj[key] = label.value;
  }
  return JSON.stringify(labelsObj, null, 2);
}

/**
 * Generate labels.d.ts for TypeScript/JS autocomplete
 */
function generateLabelsDts(labels: Label[]): string {
  const properties = labels
    .map(label => `  ${toCamelCase(label.name)}: string;`)
    .join('\n');

  return `// Generated by Taggr CLI - DO NOT EDIT
// Last updated: ${new Date().toISOString()}

declare const labels: {
${properties}
};

export default labels;
`;
}

/**
 * Ensure output directory exists
 */
async function ensureOutputDir(): Promise<void> {
  await fs.ensureDir(OUTPUT_DIR);
}

/**
 * Write a single label to labels.json (fetches all and rewrites)
 */
export async function writeLabelFile(label: Label): Promise<string> {
  await ensureOutputDir();
  
  const jsonPath = path.join(OUTPUT_DIR, 'labels.json');
  const dtsPath = path.join(OUTPUT_DIR, 'labels.d.ts');
  
  // Read existing labels if file exists
  let existingLabels: Record<string, string> = {};
  if (await fs.pathExists(jsonPath)) {
    const content = await fs.readFile(jsonPath, 'utf-8');
    existingLabels = JSON.parse(content);
  }
  
  // Add/update the label
  const key = toCamelCase(label.name);
  existingLabels[key] = label.value;
  
  // Write JSON
  await fs.writeFile(jsonPath, JSON.stringify(existingLabels, null, 2), 'utf-8');
  
  // Generate d.ts from current keys
  const dtsContent = `// Generated by Taggr CLI - DO NOT EDIT
// Last updated: ${new Date().toISOString()}

declare const labels: {
${Object.keys(existingLabels).map(k => `  ${k}: string;`).join('\n')}
};

export default labels;
`;
  await fs.writeFile(dtsPath, dtsContent, 'utf-8');
  
  return jsonPath;
}

/**
 * Write all labels to labels.json and labels.d.ts
 */
export async function writeAllLabels(labels: Label[]): Promise<string[]> {
  await ensureOutputDir();
  
  const jsonPath = path.join(OUTPUT_DIR, 'labels.json');
  const dtsPath = path.join(OUTPUT_DIR, 'labels.d.ts');
  
  // Write JSON
  const jsonContent = generateLabelsJson(labels);
  await fs.writeFile(jsonPath, jsonContent, 'utf-8');
  
  // Write TypeScript declarations
  const dtsContent = generateLabelsDts(labels);
  await fs.writeFile(dtsPath, dtsContent, 'utf-8');
  
  return [jsonPath, dtsPath];
}

/**
 * Update labels files (alias for writeAllLabels)
 */
export async function updateIndexFile(labels: Label[]): Promise<void> {
  await writeAllLabels(labels);
}

/**
 * Get the output directory path
 */
export function getOutputDir(): string {
  return path.resolve(OUTPUT_DIR);
}
